### ISSUE TITLE
Module not shown in the modules list

### ISSUE THREAD

**Issue by AndySchmitt** [DonatasL/PrestaShop-ElasticSearch#7]
Hi, 

I tried to install Prestashop-ElasticSearch module on my Prestashop 1.6.0.11 installation, but when I upload the module, I receive a "Module upload success" message. The next step should be click on "Install" to effectively install the module, but the module doesn't appear in the list.

I tried with master and dev branchs, and my shop is in a Jelastic cloud infraestruture.

How can I solve this?

**Comment by rokaszygmantas** [comment]
Hi,
After you downloaded the module, make sure that the folder's name (in the zip archive) is "elasticsearch",  otherwise it might not show up in modules list. Also, after uploading the module to prestashop, you could check if the module's folder and files inside it have sufficient permissions (755 or 777 won't hurt).

**Comment by AndySchmitt** [comment]
I changed the folder's name in zip archive from "prestashop-elasticsearch-master" to "elasticsearch", but the issue persists.

I think the permissions are OK, because I installed a lot of modules uploading a zip file without problem.

**Comment by AndySchmitt** [comment]
Ok, its working. It worked after I change my PHP from 5.4 to 5.5.
